# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoTaxonomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especie', models.CharField(max_length=200)),
                ('Descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Familia', models.CharField(max_length=200)),
                ('Descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genero', models.CharField(max_length=200)),
                ('Descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='classificacaotaxonomica',
            name='Especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Especie'),
        ),
        migrations.AddField(
            model_name='classificacaotaxonomica',
            name='Familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Familia'),
        ),
        migrations.AddField(
            model_name='classificacaotaxonomica',
            name='Genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Genero'),
        ),
    ]
